### PR TITLE
Add Node 6 support.

### PR DESCRIPTION
**Pull request by pin3da**
It should solve #137 , #138 and #142

### CODE REVIEW

**Comment by zeke** [comment]
:metal:

**Comment by jreut** [comment]
Is there anything that needs doing before this PR can be accepted? I'm happy to help, as I'd like to use Myth under Node v6!

**Comment by zeke** [comment]
> Is there anything that needs doing before this PR can be accepted?

Node 6 should be added to `.travis.yml` to ensure it's working.

If that passes I would happily merge this, but I'm not an owner of the npm package... one of the owners would need to be pinged to publish a new release.

**Comment by pin3da** [comment]
@zeke Node 6 was already added in 3e493ed38545

**Comment by zeke** [comment]
cc npm package owners: @dominicbarnes, @MoOx, @ianstormtaylor

I tried to come up with a one-liner to collect the github handles of the npm package owners, but I fell short. I got this far:

```
$ npm i -g npm-user-cli && npm owner ls myth | cut -d' ' -f1
dominicbarnes
ianstormtaylor
moox
segment-admin
segmentio
```

I thought I could pipe that to `xargs npm-user`, but it only executed the search for the first result, `dominicbarnes`. Any `xargs` / `exec` wizards in the house?

**Comment by MoOx** [comment]
FYI, I am now the maintainer of a project that achieve the same goal called [cssnext](http://cssnext.io) based on another engine (postcss). This projects support way more features and works in various versions of node ;)

**Comment by sbrl** [comment]
@MoOx Looks awesome! I think I'll use that instead then :-)

**Comment by sbrl** [comment]
And @zeke, I think you want the `-I {}` switch to xargs:

```bash
npm i -g npm-user-cli && npm owner ls myth | cut -d' ' -f1 | xargs -I {} npm-user {}
```

That limits it to 1 item per run of the command. Alternatively, you could do `xargs -n 1 npm-owner` instead I think.

**Comment by sbrl** [comment]
Any particular reason for closing this @pin3da? Leaving a comment would be really helpful.

It's confusing when a PR gets closed for seemingly no reason with no explanation :-/

**Comment by pin3da** [comment]
Sorry for closing it without any comment ):

The main reason is I was cleaning some open PRs, and this one did not have any activity in the last years. Also, I haven't been involved with nodejs in a while. 

If there is still an interest/need on it, I can open it again and fix what is necessary.

**Pull request closed without merging**
